ibm_cloud_fail_over/__init__.py,sha256=wbhBYFgjpXRsLHxkrubPZXlQQAtVu9Nj75lazY0A67c,275
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=bC0gZuePXCbd9B3-7yzTueOoDj4dyjAh0CGKP-xHXqk,25056
ibm_cloud_fail_over-1.0.9.dist-info/METADATA,sha256=mdYByoAXN3aVDc3GLIthwUeCpVrQ73hvN0FkEBuQ0Wc,7084
ibm_cloud_fail_over-1.0.9.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.9.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.9.dist-info/RECORD,,
